clients = 2
replicas = 8

hosts = [
	"hotstuff-worker-1",
	"hotstuff-worker-2",
	"hotstuff-worker-3",
	"hotstuff-worker-4",
]

# specific assignments for some hosts
[[hosts-config]]
name = "hotstuff-worker-1"
clients = 2
replicas = 0
