---
- hosts: clients
  gather_facts: no
  vars:
    rate: 10000
    time: 60
    payload: 0
    client_id: "{{ inventory_hostname | regex_replace('[^0-9]', '') }}"
  tasks:
    - name: Start clients
      shell: >
        ./hotstuffclient
        --self-id {{ client_id }}
        --exit-after {{ time }}
        --request-rate {{ rate }}
        --payload-size {{ payload }}
        --max-inflight 3200
        --benchmark
        > "$HOME/{{ inventory_hostname }}.out"
        2> "$HOME/{{ inventory_hostname }}.stderr.out"

      async: 1000
      poll: 0
      register: hotstuff_clients

- hosts: replicas
  gather_facts: no
  vars:
    batch_size: 100
    view_change: 100
  tasks:
    - name: Start servers
      shell: >
        ./hotstuffserver
        --config "$HOME/self_config.toml"
        --batch-size {{ batch_size }}
        --view-change {{ view_change }}

      async: 1000
      poll: 0

- hosts: clients
  gather_facts: no
  tasks:
    - name: Wait for clients to exit
      async_status:
        jid: "{{ hotstuff_clients.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30

- hosts: replicas
  gather_facts: no
  tasks:
    - name: Kill servers
      shell: killall -s INT hotstuffserver
      ignore_errors: yes

- hosts: clients
  gather_facts: no
  tasks:
    - name: Fetch latency data
      fetch:
        src: "$HOME/{{ inventory_hostname }}.out"
        dest: "{{ destdir }}/{{ inventory_hostname }}.out"
        flat: yes
